# Generated by Django 3.2.6 on 2021-08-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_album_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table='musician',
        ),
    ]
