# Generated by Django 3.2.6 on 2021-08-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_musician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
