# Generated by Django 3.2.6 on 2021-08-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_auto_20210817_1203'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album Details',
        ),
        migrations.AlterModelTable(
            name='musician',
            table='Musician Details',
        ),
    ]
