# Generated by Django 3.2.6 on 2021-08-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_auto_20210817_1226'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
