# Generated by Django 3.2.6 on 2021-08-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_alter_musician_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
